

export const ADD_VEGETABLE = "ADD_VEGETABLE"
export const REMOVE_VEGETABLE = "DELETE_VEGETABLE"
export const UPDATE_VEGETABLE = "UPDATE_VEGETABLE"

export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE"


export const SIGNUP_DATA_SUCCESS = "SIGNUP_DATA_SUCCESS"
export const SIGNUP_DATA_FAILURE = "SIGNUP_DATA_FAILURE"

export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS"
export const LOGIN_DATA_FAILURE = "LOGIN_DATA_FAILURE"

export const LOGOUT_DATA_SUCCESS = "LOGOUT_DATA_SUCCESS"
export const TOKEN_DATA_SUCCESS = "TOKEN_DATA_SUCCESS"
export const LOGOUT_DATA_FAILURE = "LOGOUT_DATA_FAILURE"